"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { motion } from "framer-motion"
import { Database, Layers, Shield, Zap, ArrowRight, Globe, Code } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function AboutPage() {
  return (
		<main className="min-h-screen bg-gradient-to-b from-black via-blue-950 to-black text-white">
			<Header />

			<section className="pt-32 pb-16">
				<div className="container mx-auto px-4">
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ duration: 0.6 }}
						className="text-center mb-16"
					>
						<h1 className="text-4xl md:text-5xl font-bold font-space-grotesk mb-6">
							About{" "}
							<span className="bg-gradient-to-r from-blue-400 to-purple-500 text-transparent bg-clip-text">
								Bluetune
							</span>
						</h1>
						<p className="text-gray-300 max-w-3xl mx-auto text-lg">
							Revolutionizing the music industry through blockchain technology
							and decentralized storage.
						</p>
					</motion.div>

					<div className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-20">
						<div>
							<motion.div
								initial={{ opacity: 0, x: -20 }}
								animate={{ opacity: 1, x: 0 }}
								transition={{ duration: 0.6, delay: 0.1 }}
							>
								<h2 className="text-2xl font-bold mb-4 text-blue-400">
									Our Mission
								</h2>
								<p className="text-gray-300 mb-6">
									Bluetune aims to transform how music is distributed, consumed,
									and monetized by creating a truly decentralized streaming
									platform where artists maintain control over their work and
									receive fair compensation for their art.
								</p>
								<p className="text-gray-300">
									We believe in a future where technology empowers creators
									rather than exploits them, where fans can directly support
									their favorite artists, and where the value generated by music
									flows primarily to those who create it.
								</p>
							</motion.div>
						</div>

						<div>
							<motion.div
								initial={{ opacity: 0, x: 20 }}
								animate={{ opacity: 1, x: 0 }}
								transition={{ duration: 0.6, delay: 0.1 }}
							>
								<h2 className="text-2xl font-bold mb-4 text-purple-400">
									Our Technology
								</h2>
								<p className="text-gray-300 mb-6">
									Bluetune is built on the{" "}
									<span className="text-blue-400">Sui blockchain</span> and
									utilizes the{" "}
									<span className="text-purple-400">Walrus Protocol</span> for
									decentralized storage. This powerful combination provides a
									platform that is scalable, secure, and truly user-owned.
								</p>
								<p className="text-gray-300">
									By leveraging the power of blockchain technology, we've
									created a transparent ecosystem where music files are stored
									as blobs, smart contracts handle payments, and listeners can
									stream high-quality audio directly from decentralized storage.
								</p>
							</motion.div>
						</div>
					</div>

					<motion.div
						initial={{ opacity: 0, y: 20 }}
						whileInView={{ opacity: 1, y: 0 }}
						transition={{ duration: 0.6 }}
						viewport={{ once: true }}
						className="mb-20"
					>
						<h2 className="text-3xl font-bold text-center mb-12">
							Our{" "}
							<span className="bg-gradient-to-r from-blue-400 to-purple-500 text-transparent bg-clip-text">
								Technology Stack
							</span>
						</h2>

						<div className="grid grid-cols-1 md:grid-cols-2 gap-8">
							<div className="bg-black/40 backdrop-blur-md border border-blue-900/50 rounded-lg p-6">
								<div className="flex items-center mb-4">
									<div className="p-3 bg-blue-900/30 rounded-lg mr-4">
										<Layers className="h-8 w-8 text-blue-400" />
									</div>
									<h3 className="text-xl font-bold">Sui Blockchain</h3>
								</div>
								<p className="text-gray-300 mb-4">
									Sui is a layer-1 blockchain designed for high throughput and
									low latency. It provides:
								</p>
								<ul className="space-y-2 text-gray-300">
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-blue-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Horizontally scalable architecture for high performance
										</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-blue-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Powerful object-centric model for representing digital
											assets
										</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-blue-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Move language for secure, verifiable smart contracts
										</span>
									</li>
								</ul>
							</div>

							<div className="bg-black/40 backdrop-blur-md border border-purple-900/50 rounded-lg p-6">
								<div className="flex items-center mb-4">
									<div className="p-3 bg-purple-900/30 rounded-lg mr-4">
										<Database className="h-8 w-8 text-purple-400" />
									</div>
									<h3 className="text-xl font-bold">Walrus Protocol</h3>
								</div>
								<p className="text-gray-300 mb-4">
									Walrus is a decentralized storage protocol built on Sui that
									enables:
								</p>
								<ul className="space-y-2 text-gray-300">
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-purple-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Permanent and deletable blob storage options</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-purple-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Content-addressed data with rich metadata support
										</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-purple-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Efficient streaming via HTTP Range requests</span>
									</li>
								</ul>
							</div>

							<div className="bg-black/40 backdrop-blur-md border border-green-900/50 rounded-lg p-6">
								<div className="flex items-center mb-4">
									<div className="p-3 bg-green-900/30 rounded-lg mr-4">
										<Shield className="h-8 w-8 text-green-400" />
									</div>
									<h3 className="text-xl font-bold">Security & Privacy</h3>
								</div>
								<p className="text-gray-300 mb-4">
									Our platform prioritizes security and user privacy:
								</p>
								<ul className="space-y-2 text-gray-300">
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-green-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Non-custodial wallets for complete user control</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-green-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Immutable ownership records on the blockchain</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-green-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Transparent payment system with verifiable transactions
										</span>
									</li>
								</ul>
							</div>

							<div className="bg-black/40 backdrop-blur-md border border-amber-900/50 rounded-lg p-6">
								<div className="flex items-center mb-4">
									<div className="p-3 bg-amber-900/30 rounded-lg mr-4">
										<Zap className="h-8 w-8 text-amber-400" />
									</div>
									<h3 className="text-xl font-bold">Performance</h3>
								</div>
								<p className="text-gray-300 mb-4">
									Bluetune is designed for optimal user experience:
								</p>
								<ul className="space-y-2 text-gray-300">
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-amber-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Fast streaming with minimal buffering</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-amber-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>
											Responsive UI built with modern web technologies
										</span>
									</li>
									<li className="flex items-start">
										<ArrowRight className="h-5 w-5 text-amber-400 mr-2 mt-0.5 flex-shrink-0" />
										<span>Optimized for both desktop and mobile devices</span>
									</li>
								</ul>
							</div>
						</div>
					</motion.div>

					<motion.div
						initial={{ opacity: 0, y: 20 }}
						whileInView={{ opacity: 1, y: 0 }}
						transition={{ duration: 0.6 }}
						viewport={{ once: true }}
						className="mb-20"
					>
						<h2 className="text-3xl font-bold text-center mb-12">
							The{" "}
							<span className="bg-gradient-to-r from-blue-400 to-purple-500 text-transparent bg-clip-text">
								Bluetune
							</span>{" "}
							Team
						</h2>

						<div className="grid grid-cols-1 md:grid-cols-2 gap-8">
							{/* Team member cards would go here in a real application */}
							<div className="bg-black/40 backdrop-blur-md border border-blue-900/50 rounded-lg p-6 text-center">
								<div className="w-32 h-32 rounded-full bg-gradient-to-r from-blue-500/30 to-purple-500/30 mx-auto mb-4 flex items-center justify-center">
									<Code className="h-12 w-12 text-blue-400" />
								</div>
								<h3 className="text-xl font-bold mb-1">
									Okoye Emmanuel Obiajulu
								</h3>
								<p className="text-blue-400 mb-4">Lead Frontend Developer</p>
								<p className="text-gray-300 text-sm">
									Frontend expert with 4+ years experience in decentralized
									systems and Frontend development.
								</p>
							</div>

							<div className="bg-black/40 backdrop-blur-md border border-blue-900/50 rounded-lg p-6 text-center">
								<div className="w-32 h-32 rounded-full bg-gradient-to-r from-blue-500/30 to-green-500/30 mx-auto mb-4 flex items-center justify-center">
									<Database className="h-12 w-12 text-green-400" />
								</div>
								<h3 className="text-xl font-bold mb-1">
									Alainengiya George Junior
								</h3>
								<p className="text-green-400 mb-4">Lead Blockchain Expert</p>
								<p className="text-gray-300 text-sm">
									Specialized in decentralized storage solutions with deep
									knowledge of the Walrus Protocol.
								</p>
							</div>
						</div>
					</motion.div>

					<motion.div
						initial={{ opacity: 0, y: 20 }}
						whileInView={{ opacity: 1, y: 0 }}
						transition={{ duration: 0.6 }}
						viewport={{ once: true }}
						className="text-center"
					>
						<h2 className="text-3xl font-bold mb-6">Join Our Journey</h2>
						<p className="text-gray-300 max-w-2xl mx-auto mb-8">
							We're just getting started on our mission to revolutionize the
							music industry. Whether you're an artist, listener, or developer,
							there's a place for you in the Bluetune community.
						</p>
						<div className="flex flex-col sm:flex-row gap-4 justify-center">
							<Button
								size="lg"
								className="bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600"
								asChild
							>
								<Link href="/explore">Explore Music</Link>
							</Button>
							<Button
								size="lg"
								variant="outline"
								className="border-blue-500 text-blue-400 hover:bg-blue-500/10"
								asChild
							>
								<Link
									href="https://github.com/obiajulu-gif/bluetune"
									target="_blank"
									rel="noopener noreferrer"
								>
									View on GitHub
								</Link>
							</Button>
						</div>
					</motion.div>
				</div>
			</section>

			<Footer />
		</main>
	);
}

